#!/usr/bin/env python3
# Emit the gen_avc.py YAML for an incomplete-reference dependency deadlock.
#
# Picture 0 is a WIDTH-MB reference IDR whose only slice ends cleanly after one
# macroblock, leaving the picture permanently incomplete. Picture 1 is split
# into WIDTH one-MB P slices, all of which depend on that IDR. WIDTH=17 fills the
# fixed 16-task pool and blocks the parser while it reserves the 17th task;
# smaller widths exercise the same quiescent dependency during EOS/flush. Since
# the IDR's last task already exited, no thread can complete the dependency.
#
# The scheduler must recognize that quiescent state, finalize the unresolved
# dependency with no possible writer, and resume the pending tasks. The stream
# then emits both pictures and terminates. Single-threaded decoding is a control:
# its synchronous safety net already runs a task when no dependency is ready.
#
# Usage: gen_incomplete_ref_dependency.py <out.yaml> [width]
import sys


if len(sys.argv) not in (2, 3):
    raise SystemExit("usage: gen_incomplete_ref_dependency.py <out.yaml> [width]")

WIDTH = int(sys.argv[2]) if len(sys.argv) == 3 else 17
if WIDTH < 2:
    raise SystemExit("width must be at least 2 macroblocks")


def block(lines):
    return "\n".join(lines) + "\n\n"


def intra_mb():
    return [
        "  macroblocks_cavlc:",
        "  - mb_type: 0",
        "    rem_intra4x4_pred_modes: [-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1]",
        "    intra_chroma_pred_mode: 0",
        "    coded_block_pattern: 0",
    ]


out = [block([
    "--- # Incomplete reference dependency with %d dependent tasks" % WIDTH,
    "# Generated by tests/gen_incomplete_ref_dependency.py.",
])]

out.append(block([
    "- nal_ref_idc: 3",
    "  nal_unit_type: 7",
    "  profile_idc: 66",
    "  constraint_set_flags: [0,0,0,0,0,0]",
    "  level_idc: 1.0",
    "  log2_max_frame_num: 4",
    "  pic_order_cnt_type: 0",
    "  log2_max_pic_order_cnt_lsb: 4",
    "  max_num_ref_frames: 1",
    "  gaps_in_frame_num_value_allowed_flag: 0",
    "  pic_size_in_mbs: {width: %d, height: 1}" % WIDTH,
    "  frame_mbs_only_flag: 1",
    "  direct_8x8_inference_flag: 0",
]))

out.append(block([
    "- nal_ref_idc: 3",
    "  nal_unit_type: 8",
    "  pic_parameter_set_id: 0",
    "  entropy_coding_mode_flag: 0",
    "  bottom_field_pic_order_in_frame_present_flag: 0",
    "  num_slice_groups: 1",
    "  num_ref_idx_default_active: {l0: 1, l1: 1}",
    "  weighted_pred_flag: 0",
    "  weighted_bipred_idc: 0",
    "  pic_init_qp: 0",
    "  chroma_qp_index_offset: 0",
    "  deblocking_filter_control_present_flag: 0",
    "  constrained_intra_pred_flag: 0",
    "  redundant_pic_cnt_present_flag: 0",
]))

# Reference IDR: one coded MB in a WIDTH-MB picture, so it never reaches INT_MAX.
out.append(block([
    "- nal_ref_idc: 3",
    "  nal_unit_type: 5",
    "  first_mb_in_slice: 0",
    "  slice_type: 2",
    "  pic_parameter_set_id: 0",
    "  frame_num: {bits: 4, absolute: 0}",
    "  idr_pic_id: 0",
    "  pic_order_cnt: {type: 0, bits: 4, absolute: 0}",
    "  no_output_of_prior_pics_flag: 0",
    "  long_term_reference_flag: 0",
    "  slice_qp_delta: 0",
] + intra_mb()))

# WIDTH one-MB P slices all wait on the incomplete IDR. WIDTH=17 saturates the
# task pool; smaller values leave the same permanent dependency for EOS/flush.
for first_mb in range(WIDTH):
    out.append(block([
        "- nal_ref_idc: 2",
        "  nal_unit_type: 1",
        "  first_mb_in_slice: %d" % first_mb,
        "  slice_type: 0",
        "  pic_parameter_set_id: 0",
        "  frame_num: {bits: 4, absolute: 1}",
        "  pic_order_cnt: {type: 0, bits: 4, absolute: 2}",
        "  num_ref_idx_active: {override_flag: 0, l0: 1}",
        "  slice_qp_delta: 0",
        "  macroblocks_cavlc:",
        "  - mb_skip_run: 1",
    ]))

open(sys.argv[1], "w").write("".join(out))
print("wrote %s (%d-MB incomplete IDR + %d dependent P slices)" %
      (sys.argv[1], WIDTH, WIDTH))
