#!/usr/bin/env python3
# Generate a multi-AU Stereo-High MVC YAML for tests/gen_avc.py that creates
# DPB pressure (many small 1x1 frames buffered under a paced consumer) and a
# dependent-view frame_num gap, so the AU's dependent lands at base+2 (a
# non-existing gap-fill frame between them) - the structure that exposes the
# old FrameId+1 view-pairing shortcut.
import sys

N = int(sys.argv[1]) if len(sys.argv) > 1 else 20      # total AUs (AU0 = IDR)
LAGN = int(sys.argv[2]) if len(sys.argv) > 2 else 2    # how many dependents before the shift are non-reference (-> gap size)
HOLD_POC = int(sys.argv[3]) if len(sys.argv) > 3 else 200  # unused (kept for arg compatibility)
out = sys.argv[4] if len(sys.argv) > 4 else "tests/conformance/mvc-synthetic/mvc_dependent_frame_num_gap.yaml"

def base_idr(fn, poc):
    return f"""- nal_ref_idc: 3
  nal_unit_type: 14
  non_idr_flag: 0
  priority_id: 0
  view_id: 0
  temporal_id: 0
  anchor_pic_flag: 1
  inter_view_flag: 0
- nal_ref_idc: 3
  nal_unit_type: 5
  first_mb_in_slice: 0
  slice_type: 2
  pic_parameter_set_id: 0
  frame_num: {{bits: 8, absolute: {fn}}}
  idr_pic_id: 0
  pic_order_cnt: {{type: 0, bits: 8, absolute: {poc}}}
  no_output_of_prior_pics_flag: 0
  long_term_reference_flag: 0
  slice_qp_delta: 0
  macroblocks_cavlc:
  - mb_type: 0
    rem_intra4x4_pred_modes: [-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1]
    intra_chroma_pred_mode: 0
    coded_block_pattern: 0
"""

def dep_idr(fn, poc):
    return f"""- nal_ref_idc: 3
  nal_unit_type: 20
  non_idr_flag: 0
  priority_id: 0
  view_id: 1
  temporal_id: 0
  anchor_pic_flag: 1
  inter_view_flag: 0
  first_mb_in_slice: 0
  slice_type: 2
  pic_parameter_set_id: 1
  frame_num: {{bits: 8, absolute: {fn}}}
  idr_pic_id: 0
  pic_order_cnt: {{type: 0, bits: 8, absolute: {poc}}}
  no_output_of_prior_pics_flag: 0
  long_term_reference_flag: 0
  slice_qp_delta: 0
  macroblocks_cavlc:
  - mb_type: 0
    rem_intra4x4_pred_modes: [-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1]
    intra_chroma_pred_mode: 0
    coded_block_pattern: 0
"""

def base_p(fn, poc, ref_idc=2):
    return f"""- nal_ref_idc: {ref_idc}
  nal_unit_type: 14
  non_idr_flag: 1
  priority_id: 0
  view_id: 0
  temporal_id: 0
  anchor_pic_flag: 0
  inter_view_flag: 1
- nal_ref_idc: {ref_idc}
  nal_unit_type: 1
  first_mb_in_slice: 0
  slice_type: 0
  pic_parameter_set_id: 0
  frame_num: {{bits: 8, absolute: {fn}}}
  pic_order_cnt: {{type: 0, bits: 8, absolute: {poc}}}
  num_ref_idx_active: {{override_flag: 0, l0: 1}}
  slice_qp_delta: 0
  macroblocks_cavlc:
  - mb_skip_run: 0
    mb_type: 0
    ref_idx: {{}}
    mvds: [[0,0],]
    coded_block_pattern: 0
"""

def dep_b(fn, poc, ref_idc=2):
    return f"""- nal_ref_idc: {ref_idc}
  nal_unit_type: 20
  non_idr_flag: 1
  priority_id: 0
  view_id: 1
  temporal_id: 0
  anchor_pic_flag: 0
  inter_view_flag: 0
  first_mb_in_slice: 0
  slice_type: 1
  pic_parameter_set_id: 1
  frame_num: {{bits: 8, absolute: {fn}}}
  pic_order_cnt: {{type: 0, bits: 8, absolute: {poc}}}
  direct_spatial_mv_pred_flag: 0
  num_ref_idx_active: {{override_flag: 1, l0: 2, l1: 2}}
  slice_qp_delta: 0
  macroblocks_cavlc:
  - mb_skip_run: 0
    mb_type: 3
    ref_idx: {{"0":0,"4":1}}
    mvds: [[0,0],[0,0]]
    coded_block_pattern: 0
"""

HEADERS = """--- # MVC dependent-view frame_num gap (generated by tests/gen_gap_stream.py).
# A regression guard for the access-unit view-pairing fix. Every non-anchor
# dependent view is non-reference, so the dependent view's PrevRefFrameNum never
# advances past the anchor; the final access unit's reference dependent then
# carries a large frame_num gap, and the decoder infers gap-fill frames between
# the base and its dependent (8.2.5.2), pushing the dependent's FrameId several
# past base+1. The final AU also has the lowest non-zero POC, so under a paced
# consumer it is force-bumped while the DPB is full and its dependent is not yet
# queued - the exact window the old decode-order "base+1" pairing shortcut got
# wrong. Pairing the views by (FrameNum, POC) resolves it; without the fix the
# held, mispaired frames overflow the DPB and the decoder aborts (the harness
# runs this fixture forked, so that abort is reported as a clean FAIL). All
# macroblocks are residual-free DC/zero-MV, so every decoded sample is 128 for
# both views in every frame (see ground_truth.py) - knowable without a decoder.
- nal_ref_idc: 3
  nal_unit_type: 7
  profile_idc: 66
  constraint_set_flags: [0,0,0,0,0,0]
  level_idc: 3.0
  log2_max_frame_num: 8
  pic_order_cnt_type: 0
  log2_max_pic_order_cnt_lsb: 8
  max_num_ref_frames: 4
  gaps_in_frame_num_value_allowed_flag: 1
  pic_size_in_mbs: {width: 1, height: 1}
  frame_mbs_only_flag: 1
  direct_8x8_inference_flag: 0
- nal_ref_idc: 3
  nal_unit_type: 8
  pic_parameter_set_id: 0
  entropy_coding_mode_flag: 0
  bottom_field_pic_order_in_frame_present_flag: 0
  num_slice_groups: 1
  num_ref_idx_default_active: {l0: 1, l1: 1}
  weighted_pred_flag: 0
  weighted_bipred_idc: 0
  pic_init_qp: 0
  chroma_qp_index_offset: 0
  deblocking_filter_control_present_flag: 0
  constrained_intra_pred_flag: 0
  redundant_pic_cnt_present_flag: 0
- nal_ref_idc: 3
  nal_unit_type: 15
  profile_idc: 128
  constraint_set_flags: [0,0,0,0,0,0]
  level_idc: 3.0
  chroma_format_idc: 1
  bit_depth: {luma: 8, chroma: 8}
  qpprime_y_zero_transform_bypass_flag: 0
  log2_max_frame_num: 8
  pic_order_cnt_type: 0
  log2_max_pic_order_cnt_lsb: 8
  max_num_ref_frames: 4
  gaps_in_frame_num_value_allowed_flag: 1
  pic_size_in_mbs: {width: 1, height: 1}
  frame_mbs_only_flag: 1
  direct_8x8_inference_flag: 0
  view_ids: [0,1]
  num_anchor_refs: {l0: 0, l1: 0}
  num_non_anchor_refs: {l0: 0, l1: 0}
  level_values_signalled:
    - idc: 3.0
      operation_points: [{temporal_id: 0, target_views: [0,1], num_views: 2}]
- nal_ref_idc: 3
  nal_unit_type: 8
  pic_parameter_set_id: 1
  entropy_coding_mode_flag: 0
  bottom_field_pic_order_in_frame_present_flag: 0
  num_slice_groups: 1
  num_ref_idx_default_active: {l0: 1, l1: 1}
  weighted_pred_flag: 0
  weighted_bipred_idc: 0
  pic_init_qp: 0
  chroma_qp_index_offset: 0
  deblocking_filter_control_present_flag: 0
  constrained_intra_pred_flag: 0
  redundant_pic_cnt_present_flag: 0
"""

parts = [HEADERS]
# AU0: anchor IDR, both views reference, poc 0
parts.append(base_idr(0, 0))
parts.append(dep_idr(0, 0))
# AU1..N-2 have increasing high POCs (4,6,8,...) so the decoder must hold them
# in the reorder buffer; the LAST AU is the shift-AU with the lowest non-zero
# POC (2), decoded last under full-DPB pressure, so it is the frame force-bumped
# while its (gap-shifted) dependent is still unbumped in to_get_frames.
SHIFT = N - 1            # the shift access unit (decoded last, lowest POC)
for i in range(1, N):
    poc = 2 if i == SHIFT else 2 * (i + 1)
    parts.append(base_p(i, poc, ref_idc=2))
    # the LAGN dependents right before the shift AU are non-reference, so the
    # dependent view's PrevRefFrameNum stays behind by LAGN; the shift AU's
    # reference dependent then carries a frame_num gap of LAGN+1 -> LAGN inferred
    # gap-fill frames between the base and its dependent (as on the real stream).
    dep_idc = 0 if (SHIFT - LAGN) <= i < SHIFT else 2
    parts.append(dep_b(i, poc, ref_idc=dep_idc))

with open(out, "w") as f:
    f.write("".join(parts))
print(f"wrote {out}: {N} AUs, {LAGN} non-reference dependents before the shift AU")
