#!/usr/bin/env python3
# Generate a Stereo-High MVC YAML (for tests/gen_avc.py) that exercises inter-view
# reference-picture-list construction on a *single-temporal-reference* dependent-view
# B slice - the one shape where the order of the 8.2.4.2.3 "RefPicList1 == RefPicList0
# swap" relative to the H.8.2.1 inter-view append actually changes decoded output.
#
# Structure (mirrors mvc_base, two AUs):
#   AU0 anchor IDR: base view I  -> DC intra, all 128 ; dependent view I_PCM, all 192.
#   AU1 non-anchor: base view P  -> zero-motion copy of base AU0, still 128 (this is
#                   the co-AU base = basePic / the inter-view reference) ; dependent
#                   view B -> B_L1_16x16, refIdxL1 = 0, zero MV, no residual: a pure
#                   copy of RefPicList1[0].
#
# The dependent B slice has exactly ONE temporal reference (its own IDR at POC 0), so
# after temporal init RefPicList0 == RefPicList1 == [depIDR]. Per H.8.2.1 the inter-view
# ref (basePic) is appended AFTER the 8.2.4.2.3 swap, which - on a single-entry list -
# does NOT fire, leaving RefPicList1[0] = depIDR (=192). A decoder that appends the
# inter-view ref BEFORE the swap makes RefPicList1 = [depIDR, basePic] of length 2,
# fires the swap, and wrongly promotes basePic (=128) to RefPicList1[0].
#
#   Spec-correct dependent output : frame0 = 192 (IDR), frame1 = 192 (copy of depIDR).
#   Append-before-swap bug output : frame0 = 192,        frame1 = 128 (copy of basePic).
#
# Base view is all-128 in both frames. All values are hand-derivable with no decoder;
# ground_truth.py pins the spec-correct hashes. See tests/conformance/mvc-synthetic/README.md.
import sys

out = sys.argv[1] if len(sys.argv) > 1 else "tests/conformance/mvc-synthetic/mvc_interview_reflist.yaml"

BASE = 128   # base view luma/chroma (DC intra + zero-motion P copy)
DEP  = 192   # dependent IDR luma/chroma (I_PCM) - distinct from BASE so the wrong
             # inter-view reference is observable in the decoded samples

HEADERS = """--- # Single-temporal-ref dependent-view B + inter-view reference
# (generated by tests/gen_interview_reflist_stream.py). Regression guard for the
# order of the 8.2.4.2.3 RefPicList1==RefPicList0 swap versus the H.8.2.1 inter-view
# append. Unlike the other synthetic fixtures this one is NOT all-128: the base view
# is 128 and the dependent IDR is 192, so a dependent B slice that copies
# RefPicList1[0] resolves to 192 (spec: temporal ref) or 128 (bug: inter-view ref
# promoted by a mis-ordered swap). Values are residual-free, zero-motion copies of
# I / I_PCM references, so the correct output is knowable without a decoder
# (ground_truth.py). Base = 128 in both frames; dependent = 192 in both frames.
- nal_ref_idc: 3
  nal_unit_type: 7 # Sequence parameter set (base view)
  profile_idc: 66 # Baseline
  constraint_set_flags: [0,0,0,0,0,0]
  level_idc: 1.0
  log2_max_frame_num: 4
  pic_order_cnt_type: 0
  log2_max_pic_order_cnt_lsb: 4
  max_num_ref_frames: 2
  gaps_in_frame_num_value_allowed_flag: 0
  pic_size_in_mbs: {width: 1, height: 1}
  frame_mbs_only_flag: 1
  direct_8x8_inference_flag: 0
- nal_ref_idc: 3
  nal_unit_type: 8 # Picture parameter set (base view)
  pic_parameter_set_id: 0
  entropy_coding_mode_flag: 0 # CAVLC
  bottom_field_pic_order_in_frame_present_flag: 0
  num_slice_groups: 1
  num_ref_idx_default_active: {l0: 1, l1: 1}
  weighted_pred_flag: 0
  weighted_bipred_idc: 0
  pic_init_qp: 0
  chroma_qp_index_offset: 0
  deblocking_filter_control_present_flag: 0
  constrained_intra_pred_flag: 0
  redundant_pic_cnt_present_flag: 0
- nal_ref_idc: 3
  nal_unit_type: 15 # Subset sequence parameter set (dependent view)
  profile_idc: 128 # Stereo High
  constraint_set_flags: [0,0,0,0,0,0]
  level_idc: 1.0
  chroma_format_idc: 1 # 4:2:0
  bit_depth: {luma: 8, chroma: 8}
  qpprime_y_zero_transform_bypass_flag: 0
  log2_max_frame_num: 4
  pic_order_cnt_type: 0
  log2_max_pic_order_cnt_lsb: 4
  max_num_ref_frames: 2
  gaps_in_frame_num_value_allowed_flag: 0
  pic_size_in_mbs: {width: 1, height: 1}
  frame_mbs_only_flag: 1
  direct_8x8_inference_flag: 0
  view_ids: [0,1]
  num_anchor_refs: {l0: 0, l1: 0} # anchor IDR is intra (I_PCM), no inter-view ref
  num_non_anchor_refs: {l0: 1, l1: 1} # non-anchor dependent references the base view (view_id 0) inter-view
  level_values_signalled:
    - idc: 1.0
      operation_points: [{temporal_id: 0, target_views: [0,1], num_views: 2}]
- nal_ref_idc: 3
  nal_unit_type: 8 # Picture parameter set (dependent view)
  pic_parameter_set_id: 1
  entropy_coding_mode_flag: 0 # CAVLC
  bottom_field_pic_order_in_frame_present_flag: 0
  num_slice_groups: 1
  num_ref_idx_default_active: {l0: 1, l1: 1}
  weighted_pred_flag: 0
  weighted_bipred_idc: 0
  pic_init_qp: 0
  chroma_qp_index_offset: 0
  deblocking_filter_control_present_flag: 0
  constrained_intra_pred_flag: 0
  redundant_pic_cnt_present_flag: 0
"""

# AU0: anchor IDR - base view (DC intra, 128) then dependent view (I_PCM, 192)
AU0_BASE = """# --- AU 0: anchor IDR ---
- nal_ref_idc: 3
  nal_unit_type: 14 # Prefix NAL unit
  non_idr_flag: 0
  priority_id: 0
  view_id: 0
  temporal_id: 0
  anchor_pic_flag: 1
  inter_view_flag: 0
- nal_ref_idc: 3
  nal_unit_type: 5 # Coded slice of an IDR picture (base view)
  first_mb_in_slice: 0
  slice_type: 2 # I
  pic_parameter_set_id: 0
  frame_num: {bits: 4, absolute: 0}
  idr_pic_id: 0
  pic_order_cnt: {type: 0, bits: 4, absolute: 0}
  no_output_of_prior_pics_flag: 0
  long_term_reference_flag: 0
  slice_qp_delta: 0
  macroblocks_cavlc:
  - mb_type: 0
    rem_intra4x4_pred_modes: [-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1]
    intra_chroma_pred_mode: 0
    coded_block_pattern: 0
"""

def dep_idr_pcm(val):
    Y  = ",".join(str(val) for _ in range(256))
    Cb = ",".join(str(val) for _ in range(64))
    Cr = ",".join(str(val) for _ in range(64))
    return f"""- nal_ref_idc: 3
  nal_unit_type: 20 # Coded slice extension (dependent view, I_PCM = {val})
  non_idr_flag: 0
  priority_id: 0
  view_id: 1
  temporal_id: 0
  anchor_pic_flag: 1
  inter_view_flag: 0
  first_mb_in_slice: 0
  slice_type: 2 # I
  pic_parameter_set_id: 1
  frame_num: {{bits: 4, absolute: 0}}
  idr_pic_id: 0
  pic_order_cnt: {{type: 0, bits: 4, absolute: 0}}
  no_output_of_prior_pics_flag: 0
  long_term_reference_flag: 0
  slice_qp_delta: 0
  macroblocks_cavlc:
  - mb_type: 25 # I_PCM
    pcm_samples: {{bits_Y: 8, bits_C: 8, Y: [{Y}], Cb: [{Cb}], Cr: [{Cr}]}}
"""

# AU1: non-anchor - base view P (zero-motion copy of base AU0 = 128) then dependent
# view B (B_L1_16x16, refIdxL1 = 0, zero MV, no residual = copy of RefPicList1[0]).
AU1 = """# --- AU 1: non-anchor (base P copy, dependent B_L1 copy of RefPicList1[0]) ---
- nal_ref_idc: 2
  nal_unit_type: 14 # Prefix NAL unit
  non_idr_flag: 1
  priority_id: 0
  view_id: 0
  temporal_id: 0
  anchor_pic_flag: 0
  inter_view_flag: 1
- nal_ref_idc: 2
  nal_unit_type: 1 # Coded slice of a non-IDR picture (base view P)
  first_mb_in_slice: 0
  slice_type: 0 # P
  pic_parameter_set_id: 0
  frame_num: {bits: 4, absolute: 1}
  pic_order_cnt: {type: 0, bits: 4, absolute: 1}
  num_ref_idx_active: {override_flag: 0, l0: 1}
  slice_qp_delta: 0
  macroblocks_cavlc:
  - mb_skip_run: 0
    mb_type: 0 # P_L0_16x16, zero MV -> copies base AU0 (128)
    ref_idx: {}
    mvds: [[0,0],]
    coded_block_pattern: 0
- nal_ref_idc: 2
  nal_unit_type: 20 # Coded slice extension (dependent view B)
  non_idr_flag: 1
  priority_id: 0
  view_id: 1
  temporal_id: 0
  anchor_pic_flag: 0
  inter_view_flag: 0
  first_mb_in_slice: 0
  slice_type: 1 # B
  pic_parameter_set_id: 1
  frame_num: {bits: 4, absolute: 1}
  pic_order_cnt: {type: 0, bits: 4, absolute: 1}
  direct_spatial_mv_pred_flag: 0
  num_ref_idx_active: {override_flag: 1, l0: 1, l1: 1} # single ref each list -> refIdx inferred 0
  slice_qp_delta: 0
  macroblocks_cavlc:
  - mb_skip_run: 0
    mb_type: 2 # B_L1_16x16 -> predicts from RefPicList1[0] only
    ref_idx: {} # num_ref_idx_l1_active == 1 -> refIdxL1 inferred 0
    mvds: [[0,0],] # single L1 mvd, zero -> zero MV copy
    coded_block_pattern: 0
"""

with open(out, "w") as f:
    f.write(HEADERS)
    f.write(AU0_BASE)
    f.write(dep_idr_pcm(DEP))
    f.write(AU1)
print(f"wrote {out}: 2 AUs, base={BASE} dep={DEP}")
